install:
  - set QTDIR=C:\Qt\5.7\msvc2013_64
  - set PATH=%PATH%;%QTDIR%\bin;C:\Qt\QtIFW2.0.1\bin
  - call "%VS120COMNTOOLS%\..\..\VC\vcvarsall.bat" x86_amd64
build_script:
  - git submodule update --init --recursive
  - qmake neuronify.pro
  - nmake
  - nmake clean
  - set INSTALLER_DIR=installer\packages\net.ovilab.neuronify\data
  - xcopy /s "release" "%INSTALLER_DIR%"
  - xcopy /s "%QTDIR%\qml" "%INSTALLER_DIR%"
  - xcopy /s "%VS120COMNTOOLS%\..\..\VC\redist\x64\Microsoft.VC120.CRT" "%INSTALLER_DIR%"
  - windeployqt.exe -quick -quickwidgets -multimediaquick -multimedia -opengl -quickparticles -quickwidgets -qmldir . "%INSTALLER_DIR%"
  - binarycreator.exe -c installer/config/config.xml -p installer/packages neuronify-windows-installer
artifacts:
  - path: neuronify-windows-installer.exe
    name: neuronify-windows-installer
    type: File
  - path: installer\packages\net.ovilab.neuronify\data
    name: neuronify-windows
    type: zip
deploy:
  description: 'Automated Windows build'
  provider: GitHub
  auth_token:
    secure: 6LmZ/bebQkiHy0uDmhrqvG/0LEQOTaAgHARYLmdjPEpyuPhBDIOrhPn+vArd01Kv
  artifact: /.*\.(exe|zip)/
  draft: false
  prerelease: true
  force_update: true
  on:
    appveyor_repo_tag: true
