image:
  - Visual Studio 2017
install:
  - dir C:\Qt\Tools\QtInstallerFramework\3.1\bin
  - dir C:\Qt\5.12.4\msvc2017_64\bin
  - set QTDIR=C:\Qt\5.12.4\msvc2017_64
  - set PATH=%PATH%;%QTDIR%\bin;C:\Qt\QtIFW2.0.1\bin;C:\Qt\Tools\QtInstallerFramework\3.1\bin
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"
  - cmd: pip.exe install conan
  - cmd: conan user
  - cmd: conan --version
build_script:
  - conan install . -s compiler="Visual Studio" -s compiler.version=14
  - git submodule update --init --recursive
  - qmake neuronify.pro
  - nmake
  - nmake clean
  - set INSTALLER_DIR=installer\packages\net.ovilab.neuronify\data
  - xcopy /s "release" "%INSTALLER_DIR%"
  - xcopy /s "%QTDIR%\qml" "%INSTALLER_DIR%"
  #- xcopy /s "%VS140COMNTOOLS%\..\..\VC\redist\x64\Microsoft.VC140.CRT" "%INSTALLER_DIR%"
  #- windeployqt.exe -quick -quickwidgets -multimediaquick -multimedia -opengl -quickparticles -quickwidgets -qmldir . "%INSTALLER_DIR%"
  - xcopy /s "%QTDIR%\bin\Qt5MultimediaQuick.dll" "%INSTALLER_DIR%"
  - windeployqt.exe -quick -quickwidgets -multimedia -opengl -quickparticles -quickwidgets -qmldir . "%INSTALLER_DIR%"
  - binarycreator.exe -c installer/config/config.xml -p installer/packages neuronify-windows-installer
artifacts:
  - path: neuronify-windows-installer.exe
    name: neuronify-windows-installer
    type: File
  - path: installer\packages\net.ovilab.neuronify\data
    name: neuronify-windows
    type: zip
deploy:
  description: 'Automated Windows build'
  provider: GitHub
  auth_token:
    secure: 6LmZ/bebQkiHy0uDmhrqvG/0LEQOTaAgHARYLmdjPEpyuPhBDIOrhPn+vArd01Kv
  artifact: /.*\.(exe|zip)/
  draft: false
  prerelease: true
  on:
    branch: /release\/.+/
    APPVEYOR_REPO_TAG: true
